#!/usr/bin/env bash

SCRIPT_PATH=$( readlink --canonicalize $( dirname $0 ) )
#ROOT_PATH=$( readlink --canonicalize $SCRIPT_PATH )
ROOT_PATH=$( readlink --canonicalize . )

#g++ $ROOT_PATH/src/main.cpp -v -o $ROOT_PATH/main -Og -g3 -std=c++17 -lSDL2 -lSDL2_image -I./lib
g++ $ROOT_PATH/src/main.cpp -v -o $ROOT_PATH/main -g3 -std=c++17 -lSDL2 -lSDL2_image -I./lib -Wno-format-security
#g++ $ROOT_PATH/src/main.cpp -v -o $ROOT_PATH/main -g3 -std=c++23 -lSDL2 -lSDL2_image -I./lib


if [ $? == 0 ]; then
  clear

  #cat $ROOT_PATH/assets/title.asc

  $ROOT_PATH/main
  #valgrind --leak-check=full --track-origins=yes $ROOT_PATH/main

  rm -f $ROOT_PATH/main
fi

